# Generated by Django 5.1.1 on 2024-10-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0002_cruise_inforequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoRequest',
        ),
        migrations.AlterField(
            model_name='cruise',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
