# Generated by Django 5.1.1 on 2024-10-02 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0003_delete_inforequest_alter_cruise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cruises', to='relecloud.destination'),
        ),
    ]
