# Generated by Django 5.1.1 on 2024-10-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0004_cruise_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='destination',
        ),
        migrations.AddField(
            model_name='cruise',
            name='departure_date',
            field=models.DateField(default='2024-01-01', null=True),
        ),
        migrations.AddField(
            model_name='cruise',
            name='duration',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name='cruise',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, null=True),
        ),
    ]
