# Generated by Django 5.1.1 on 2024-10-11 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0005_remove_cruise_destination_cruise_departure_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relecloud.destination'),
        ),
    ]
